/*
   This file was generated automatically by the Mojo IDE version B1.3.4.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module adder8_5 (
    input [7:0] a,
    input [7:0] b,
    input alufn,
    output reg [7:0] ao,
    output reg z,
    output reg v,
    output reg n,
    output reg [7:0] out
  );
  
  
  
  reg [7:0] sum;
  
  reg [7:0] xB;
  
  always @* begin
    ao = a;
    xB = b ^ {4'h8{alufn}};
    sum = a + xB + alufn;
    z = (~|sum);
    v = (a[7+0-:1] & xB[7+0-:1] & ~sum[7+0-:1]) | (~a[7+0-:1] & ~xB[7+0-:1] & sum[7+0-:1]);
    n = sum[7+0-:1];
    out = sum;
  end
endmodule
