/*
   This file was generated automatically by the Mojo IDE version B1.3.4.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module finitestatemachine_2 (
    input clk,
    input rst,
    input [4:0] io_button,
    output reg out,
    output reg [23:0] io_led
  );
  
  
  
  wire [1-1:0] M_test_add_out;
  wire [1-1:0] M_test_add_done;
  test_adder8_4 test_add (
    .clk(clk),
    .rst(rst),
    .out(M_test_add_out),
    .done(M_test_add_done)
  );
  localparam IDLE_state = 3'd0;
  localparam ADD_state = 3'd1;
  localparam BOOL_state = 3'd2;
  localparam CMP_state = 3'd3;
  localparam SHIFT_state = 3'd4;
  localparam DONE_state = 3'd5;
  
  reg [2:0] M_state_d, M_state_q = IDLE_state;
  
  always @* begin
    M_state_d = M_state_q;
    
    M_state_d = M_state_q;
    io_led = 24'h000000;
    out = 1'h0;
    
    case (M_state_q)
      IDLE_state: begin
        if (io_button[0+0-:1]) begin
          M_state_d = ADD_state;
        end
      end
      ADD_state: begin
        io_led[0+0+0-:1] = 1'h1;
        out = M_test_add_out;
        if (M_test_add_done == 1'h1) begin
          io_led[0+1+0-:1] = 1'h1;
          M_state_d = IDLE_state;
        end
      end
    endcase
  end
  
  always @(posedge clk) begin
    if (rst == 1'b1) begin
      M_state_q <= 1'h0;
    end else begin
      M_state_q <= M_state_d;
    end
  end
  
endmodule
