/*
   This file was generated automatically by the Mojo IDE version B1.3.4.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module compare8_7 (
    input z,
    input v,
    input n,
    input [1:0] alufn,
    output reg [7:0] out
  );
  
  
  
  reg less;
  
  reg lessequal;
  
  always @* begin
    less = n ^ v;
    lessequal = z | (n ^ v);
    
    case (alufn)
      2'h1: begin
        out = {7'h00, z};
      end
      2'h2: begin
        out = {7'h00, less};
      end
      2'h3: begin
        out = {7'h00, lessequal};
      end
      default: begin
        out = {7'h00, z};
      end
    endcase
  end
endmodule
